export const countries = [
  { eng_name: "Albania", cro_name: "Albanija" },
  { eng_name: "Andorra", cro_name: "Andora" },
  { eng_name: "Austria", cro_name: "Austrija" },
  { eng_name: "Belarus", cro_name: "Bjelorusija" },
  { eng_name: "Belgium", cro_name: "Belgija" },
  { eng_name: "Bosnia and Herz.", cro_name: "Bosna i Hercegovina" },
  { eng_name: "Bulgaria", cro_name: "Bugarska" },
  { eng_name: "Croatia", cro_name: "Hrvatska" },
  { eng_name: "Cyprus", cro_name: "Cipar" },
  { eng_name: "Czech Rep.", cro_name: "Češka" },
  { eng_name: "Denmark", cro_name: "Danska" },
  { eng_name: "Estonia", cro_name: "Estonija" },
  { eng_name: "Finland", cro_name: "Finska" },
  { eng_name: "France", cro_name: "Francuska" },
  { eng_name: "Germany", cro_name: "Njemačka" },
  { eng_name: "Greece", cro_name: "Grčka" },
  { eng_name: "Hungary", cro_name: "Mađarska" },
  { eng_name: "Iceland", cro_name: "Island" },
  { eng_name: "Ireland", cro_name: "Irska" },
  { eng_name: "Italy", cro_name: "Italija" },
  { eng_name: "Latvia", cro_name: "Latvija" },
  { eng_name: "Liechtenstein", cro_name: "Lihtenštajn" },
  { eng_name: "Lithuania", cro_name: "Litva" },
  { eng_name: "Luxembourg", cro_name: "Luksemburg" },
  { eng_name: "Malta", cro_name: "Malta" },
  { eng_name: "Moldova", cro_name: "Moldova" },
  { eng_name: "Monaco", cro_name: "Monako" },
  { eng_name: "Montenegro", cro_name: "Crna Gora" },
  { eng_name: "Netherlands", cro_name: "Nizozemska" },
  { eng_name: "North Macedonia", cro_name: "Sjeverna Makedonija" },
  { eng_name: "Norway", cro_name: "Norveška" },
  { eng_name: "Poland", cro_name: "Poljska" },
  { eng_name: "Portugal", cro_name: "Portugal" },
  { eng_name: "Romania", cro_name: "Rumunjska" },
  { eng_name: "Russia", cro_name: "Rusija" },
  { eng_name: "San Marino", cro_name: "San Marino" },
  { eng_name: "Serbia", cro_name: "Srbija" },
  { eng_name: "Slovakia", cro_name: "Slovačka" },
  { eng_name: "Slovenia", cro_name: "Slovenija" },
  { eng_name: "Spain", cro_name: "Španjolska" },
  { eng_name: "Sweden", cro_name: "Švedska" },
  { eng_name: "Switzerland", cro_name: "Švicarska" },
  { eng_name: "Ukraine", cro_name: "Ukrajina" },
  { eng_name: "United Kingdom", cro_name: "Ujedinjeno Kraljevstvo" },
  { eng_name: "Vatican City", cro_name: "Vatikan" },
  { eng_name: "N. Cyprus", cro_name: "Sjeverni Cipar" },
];
