// client/utils/bestTimeToVisitData.ts
export type WeatherIconKey =
  | "sunny"
  | "partly_cloudy"
  | "cloudy"
  | "rain"
  | "showers"
  | "snow"
  | "wind"
  | "fog";

export type MonthKey =
  | "jan"
  | "feb"
  | "mar"
  | "apr"
  | "may"
  | "jun"
  | "jul"
  | "aug"
  | "sep"
  | "oct"
  | "nov"
  | "dec";

export type RegionClimate = {
  id: string;
  label: string; // npr. "Obala (Dalmacija)"
  note?: string; // npr. "Najugodnije: proljeće i rana jesen..."
  months: Array<{
    month: MonthKey;
    tempC: number; // prosječna temp
    rainMm: number; // prosječne padaline
    // opcionalno: ako želiš ručno forsirati ikonu ili ocjenu
    icon?: WeatherIconKey;
  }>;
};

export type CountryClimate = {
  slug: string; // slug kao u URL-u: "hrvatska", "sad", "južnoafrička republika" (bolje koristi decodeURIComponent na ulazu)
  title?: string; // npr. "Najbolje vrijeme za posjet Hrvatskoj"
  subtitle?: string; // kratko ispod naslova
  regions: RegionClimate[];
};

export const BEST_TIME_DATA: CountryClimate[] = [
{
  slug: "austrija",
  title: "Najbolje vrijeme za posjet Austriji",
  subtitle: "Alpe su hladnije, gradovi ugodniji u proljeće i jesen.",
  regions: [
    {
      id: "bec",
      label: "Beč i nizine",
      note: "Najugodnije: travanj–lipanj i rujan–listopad. Ljeto toplo, zima hladna.",
      months: [
        { month: "jan", tempC: -1, rainMm: 38 },
        { month: "feb", tempC: 1, rainMm: 42 },
        { month: "mar", tempC: 5, rainMm: 41 },
        { month: "apr", tempC: 9, rainMm: 51 },
        { month: "may", tempC: 15, rainMm: 61 },
        { month: "jun", tempC: 18, rainMm: 74 },
        { month: "jul", tempC: 19, rainMm: 63 },
        { month: "aug", tempC: 19, rainMm: 58 },
        { month: "sep", tempC: 18, rainMm: 45 },
        { month: "oct", tempC: 10, rainMm: 41 },
        { month: "nov", tempC: 5, rainMm: 50 },
        { month: "dec", tempC: -1, rainMm: 43 },
      ],
    },
    {
      id: "alpe",
      label: "Alpe (Salzburg, Tirol)",
      note: "Skijanje: prosinac–ožujak. Planinarenje: lipanj–rujan.",
      months: [
        { month: "jan", tempC: -3, rainMm: 60 },
        { month: "feb", tempC: -2, rainMm: 55 },
        { month: "mar", tempC: 2, rainMm: 65 },
        { month: "apr", tempC: 6, rainMm: 75 },
        { month: "may", tempC: 11, rainMm: 95 },
        { month: "jun", tempC: 15, rainMm: 120 },
        { month: "jul", tempC: 17, rainMm: 135 },
        { month: "aug", tempC: 17, rainMm: 125 },
        { month: "sep", tempC: 13, rainMm: 95 },
        { month: "oct", tempC: 8, rainMm: 80 },
        { month: "nov", tempC: 2, rainMm: 75 },
        { month: "dec", tempC: -2, rainMm: 70 },
      ],
    },
  ],
},

{
  slug: "bosna i hercegovina",
  title: "Najbolje vrijeme za posjet Bosni i Hercegovini",
  subtitle: "Planine su hladnije, Hercegovina je znatno toplija.",
  regions: [
    {
      id: "sarajevo",
      label: "Središnja BiH (Sarajevo)",
      note: "Najugodnije: svibanj–lipanj i rujan. Zimi često snijeg.",
      months: [
        { month: "jan", tempC: 0, rainMm: 65 },
        { month: "feb", tempC: 2, rainMm: 60 },
        { month: "mar", tempC: 7, rainMm: 65 },
        { month: "apr", tempC: 12, rainMm: 70 },
        { month: "may", tempC: 17, rainMm: 85 },
        { month: "jun", tempC: 20, rainMm: 90 },
        { month: "jul", tempC: 23, rainMm: 70 },
        { month: "aug", tempC: 23, rainMm: 65 },
        { month: "sep", tempC: 19, rainMm: 70 },
        { month: "oct", tempC: 13, rainMm: 75 },
        { month: "nov", tempC: 7, rainMm: 85 },
        { month: "dec", tempC: 2, rainMm: 80 },
      ],
    },
    {
      id: "hercegovina",
      label: "Hercegovina (Mostar)",
      note: "Najugodnije: travanj–lipanj i rujan–listopad. Ljeto je jako vruće.",
      months: [
        { month: "jan", tempC: 8, rainMm: 120 },
        { month: "feb", tempC: 10, rainMm: 110 },
        { month: "mar", tempC: 13, rainMm: 95 },
        { month: "apr", tempC: 17, rainMm: 85 },
        { month: "may", tempC: 22, rainMm: 70 },
        { month: "jun", tempC: 26, rainMm: 45 },
        { month: "jul", tempC: 30, rainMm: 20 },
        { month: "aug", tempC: 30, rainMm: 25 },
        { month: "sep", tempC: 25, rainMm: 55 },
        { month: "oct", tempC: 19, rainMm: 110 },
        { month: "nov", tempC: 13, rainMm: 140 },
        { month: "dec", tempC: 9, rainMm: 140 },
      ],
    },
  ],
},

{
  slug: "bugarska",
  title: "Najbolje vrijeme za posjet Bugarskoj",
  subtitle: "More ljeti, gradovi i planine najbolji u proljeće i jesen.",
  regions: [
    {
      id: "sofija",
      label: "Sofija i unutrašnjost",
      note: "Najugodnije: svibanj–lipanj i rujan. Zimi hladno, zna biti snijega.",
      months: [
        { month: "jan", tempC: 0, rainMm: 45 },
        { month: "feb", tempC: 2, rainMm: 40 },
        { month: "mar", tempC: 7, rainMm: 45 },
        { month: "apr", tempC: 13, rainMm: 55 },
        { month: "may", tempC: 18, rainMm: 75 },
        { month: "jun", tempC: 22, rainMm: 70 },
        { month: "jul", tempC: 25, rainMm: 55 },
        { month: "aug", tempC: 25, rainMm: 45 },
        { month: "sep", tempC: 20, rainMm: 45 },
        { month: "oct", tempC: 14, rainMm: 55 },
        { month: "nov", tempC: 7, rainMm: 55 },
        { month: "dec", tempC: 2, rainMm: 55 },
      ],
    },
    {
      id: "crno-more",
      label: "Crno more (Varna/Burgas)",
      note: "Najbolje za kupanje: lipanj–rujan.",
      months: [
        { month: "jan", tempC: 6, rainMm: 45 },
        { month: "feb", tempC: 7, rainMm: 40 },
        { month: "mar", tempC: 9, rainMm: 45 },
        { month: "apr", tempC: 13, rainMm: 40 },
        { month: "may", tempC: 18, rainMm: 45 },
        { month: "jun", tempC: 23, rainMm: 45 },
        { month: "jul", tempC: 26, rainMm: 30 },
        { month: "aug", tempC: 26, rainMm: 35 },
        { month: "sep", tempC: 22, rainMm: 40 },
        { month: "oct", tempC: 16, rainMm: 50 },
        { month: "nov", tempC: 11, rainMm: 55 },
        { month: "dec", tempC: 7, rainMm: 55 },
      ],
    },
  ],
},

{
  slug: "češka",
  title: "Najbolje vrijeme za posjet Češkoj",
  subtitle: "Najugodnije u proljeće i ranu jesen; zima hladna i često maglovita.",
  regions: [
    {
      id: "prag",
      label: "Prag i Bohemija",
      note: "Najbolje: travanj–lipanj i rujan. Zimi hladno.",
      months: [
        { month: "jan", tempC: 0, rainMm: 25 },
        { month: "feb", tempC: 2, rainMm: 25 },
        { month: "mar", tempC: 7, rainMm: 30 },
        { month: "apr", tempC: 12, rainMm: 35 },
        { month: "may", tempC: 17, rainMm: 60 },
        { month: "jun", tempC: 20, rainMm: 70 },
        { month: "jul", tempC: 22, rainMm: 65 },
        { month: "aug", tempC: 22, rainMm: 70 },
        { month: "sep", tempC: 18, rainMm: 45 },
        { month: "oct", tempC: 12, rainMm: 35 },
        { month: "nov", tempC: 6, rainMm: 35 },
        { month: "dec", tempC: 2, rainMm: 30 },
      ],
    },
  ],
},

{
  slug: "cipar",
  title: "Najbolje vrijeme za posjet Cipru",
  subtitle: "Proljeće i jesen su idealni; ljeto je jako vruće i suho.",
  regions: [
    {
      id: "obalni",
      label: "Obala (Larnaca, Paphos, Ayia Napa)",
      note: "Najbolje: travanj–lipanj i rujan–listopad. Zimi blaže, ali kišovitije.",
      months: [
        { month: "jan", tempC: 16, rainMm: 80 },
        { month: "feb", tempC: 16, rainMm: 60 },
        { month: "mar", tempC: 18, rainMm: 40 },
        { month: "apr", tempC: 21, rainMm: 25 },
        { month: "may", tempC: 25, rainMm: 10 },
        { month: "jun", tempC: 29, rainMm: 2 },
        { month: "jul", tempC: 32, rainMm: 0 },
        { month: "aug", tempC: 33, rainMm: 0 },
        { month: "sep", tempC: 30, rainMm: 5 },
        { month: "oct", tempC: 26, rainMm: 25 },
        { month: "nov", tempC: 21, rainMm: 40 },
        { month: "dec", tempC: 17, rainMm: 70 },
      ],
    },
  ],
},

{
  slug: "crna gora",
  title: "Najbolje vrijeme za posjet Crnoj Gori",
  subtitle: "Obala ima mediteransku klimu, planine su hladnije i kišovitije.",
  regions: [
    {
      id: "obala",
      label: "Obala (Kotor, Budva)",
      note: "Najbolje: svibanj–lipanj i rujan. Srpanj/kolovoz vrući i gužvoviti.",
      months: [
        { month: "jan", tempC: 9, rainMm: 170 },
        { month: "feb", tempC: 10, rainMm: 160 },
        { month: "mar", tempC: 12, rainMm: 140 },
        { month: "apr", tempC: 15, rainMm: 110 },
        { month: "may", tempC: 20, rainMm: 80 },
        { month: "jun", tempC: 24, rainMm: 60 },
        { month: "jul", tempC: 27, rainMm: 35 },
        { month: "aug", tempC: 27, rainMm: 45 },
        { month: "sep", tempC: 23, rainMm: 90 },
        { month: "oct", tempC: 18, rainMm: 160 },
        { month: "nov", tempC: 13, rainMm: 220 },
        { month: "dec", tempC: 10, rainMm: 200 },
      ],
    },
    {
      id: "planine",
      label: "Planine (Durmitor, Žabljak)",
      note: "Najbolje: lipanj–rujan za planinarenje. Zimi snijeg i skijanje.",
      months: [
        { month: "jan", tempC: -2, rainMm: 90 },
        { month: "feb", tempC: -1, rainMm: 85 },
        { month: "mar", tempC: 3, rainMm: 90 },
        { month: "apr", tempC: 7, rainMm: 95 },
        { month: "may", tempC: 12, rainMm: 105 },
        { month: "jun", tempC: 16, rainMm: 95 },
        { month: "jul", tempC: 18, rainMm: 70 },
        { month: "aug", tempC: 18, rainMm: 75 },
        { month: "sep", tempC: 14, rainMm: 90 },
        { month: "oct", tempC: 9, rainMm: 95 },
        { month: "nov", tempC: 3, rainMm: 95 },
        { month: "dec", tempC: -1, rainMm: 95 },
      ],
    },
  ],
},

{
  slug: "francuska",
  title: "Najbolje vrijeme za posjet Francuskoj",
  subtitle: "Ovdje su podaci za Pariz (kao regija).",
  regions: [
    {
      id: "pariz",
      label: "Pariz",
      note: "Najugodnije: svibanj–lipanj i rujan. Zimi je hladno i sivo.",
      months: [
        { month: "jan", tempC: 5, rainMm: 55 },
        { month: "feb", tempC: 6, rainMm: 45 },
        { month: "mar", tempC: 10, rainMm: 50 },
        { month: "apr", tempC: 13, rainMm: 50 },
        { month: "may", tempC: 17, rainMm: 55 },
        { month: "jun", tempC: 20, rainMm: 55 },
        { month: "jul", tempC: 23, rainMm: 60 },
        { month: "aug", tempC: 23, rainMm: 55 },
        { month: "sep", tempC: 19, rainMm: 50 },
        { month: "oct", tempC: 14, rainMm: 55 },
        { month: "nov", tempC: 9, rainMm: 55 },
        { month: "dec", tempC: 6, rainMm: 55 },
      ],
    },
  ],
},

{
  slug: "grčka",
  title: "Najbolje vrijeme za posjet Grčkoj",
  subtitle: "Najugodnije u proljeće i ranu jesen; ljeto je vruće i suho.",
  regions: [
    {
      id: "atenapeljepones",
      label: "Atena i Peloponez",
      note: "Najbolje: travanj–lipanj i rujan–listopad.",
      months: [
        { month: "jan", tempC: 11, rainMm: 50 },
        { month: "feb", tempC: 12, rainMm: 45 },
        { month: "mar", tempC: 14, rainMm: 40 },
        { month: "apr", tempC: 18, rainMm: 25 },
        { month: "may", tempC: 23, rainMm: 15 },
        { month: "jun", tempC: 28, rainMm: 10 },
        { month: "jul", tempC: 32, rainMm: 5 },
        { month: "aug", tempC: 32, rainMm: 5 },
        { month: "sep", tempC: 27, rainMm: 15 },
        { month: "oct", tempC: 21, rainMm: 45 },
        { month: "nov", tempC: 16, rainMm: 55 },
        { month: "dec", tempC: 12, rainMm: 60 },
      ],
    },
    {
      id: "otoci",
      label: "Otoci (Kreta/Kikladi)",
      note: "Najbolje: svibanj–lipanj i rujan. Vjetrovito ljeti (meltemi).",
      months: [
        { month: "jan", tempC: 13, rainMm: 80 },
        { month: "feb", tempC: 13, rainMm: 70 },
        { month: "mar", tempC: 15, rainMm: 55 },
        { month: "apr", tempC: 18, rainMm: 30 },
        { month: "may", tempC: 22, rainMm: 15 },
        { month: "jun", tempC: 26, rainMm: 5 },
        { month: "jul", tempC: 29, rainMm: 1 },
        { month: "aug", tempC: 29, rainMm: 2 },
        { month: "sep", tempC: 26, rainMm: 10 },
        { month: "oct", tempC: 22, rainMm: 45 },
        { month: "nov", tempC: 18, rainMm: 65 },
        { month: "dec", tempC: 14, rainMm: 85 },
      ],
    },
  ],
},

{
  slug: "hrvatska",
  title: "Najbolje vrijeme za posjet Hrvatskoj",
  subtitle: "Jadran i kontinentalni dio imaju različite sezone.",
  regions: [
    {
      id: "jadran",
      label: "Jadran",
      note: "Najugodnije: svibanj, lipanj, rujan. Srpanj/kolovoz su vrući i suhi.",
      months: [
        { month: "jan", tempC: 9, rainMm: 90 },
        { month: "feb", tempC: 10, rainMm: 80 },
        { month: "mar", tempC: 12, rainMm: 75 },
        { month: "apr", tempC: 15, rainMm: 70 },
        { month: "may", tempC: 20, rainMm: 55 },
        { month: "jun", tempC: 24, rainMm: 45 },
        { month: "jul", tempC: 27, rainMm: 25 },
        { month: "aug", tempC: 27, rainMm: 35 },
        { month: "sep", tempC: 23, rainMm: 55 },
        { month: "oct", tempC: 18, rainMm: 90 },
        { month: "nov", tempC: 13, rainMm: 110 },
        { month: "dec", tempC: 10, rainMm: 105 },
      ],
    },
    {
      id: "Kontinentalna Hrvatska",
      label: "Kontinentalna Hrvatska",
      note: "Najugodnije: kasno proljeće i rana jesen. Zimi hladno i maglovito.",
      months: [
        { month: "jan", tempC: 3, rainMm: 55 },
        { month: "feb", tempC: 6, rainMm: 50 },
        { month: "mar", tempC: 11, rainMm: 55 },
        { month: "apr", tempC: 15, rainMm: 65 },
        { month: "may", tempC: 20, rainMm: 80 },
        { month: "jun", tempC: 24, rainMm: 95 },
        { month: "jul", tempC: 27, rainMm: 75 },
        { month: "aug", tempC: 27, rainMm: 80 },
        { month: "sep", tempC: 22, rainMm: 85 },
        { month: "oct", tempC: 16, rainMm: 80 },
        { month: "nov", tempC: 10, rainMm: 80 },
        { month: "dec", tempC: 5, rainMm: 65 },
      ],
    },
  ],
},

{
  slug: "italija",
  title: "Najbolje vrijeme za posjet Italiji",
  subtitle: "Sjever ima izraženije zime; srednja Italija je odlična u proljeće i jesen.",
  regions: [
    {
      id: "sjever",
      label: "Sjever (Milano, Venecija)",
      note: "Najbolje: travanj–lipanj i rujan. Zimi hladnije i maglovito.",
      months: [
        { month: "jan", tempC: 4, rainMm: 55 },
        { month: "feb", tempC: 6, rainMm: 50 },
        { month: "mar", tempC: 11, rainMm: 60 },
        { month: "apr", tempC: 15, rainMm: 75 },
        { month: "may", tempC: 20, rainMm: 85 },
        { month: "jun", tempC: 24, rainMm: 75 },
        { month: "jul", tempC: 27, rainMm: 60 },
        { month: "aug", tempC: 27, rainMm: 70 },
        { month: "sep", tempC: 22, rainMm: 75 },
        { month: "oct", tempC: 16, rainMm: 85 },
        { month: "nov", tempC: 10, rainMm: 80 },
        { month: "dec", tempC: 5, rainMm: 65 },
      ],
    },
    {
      id: "srednja",
      label: "Srednja Italija (Rim, Firenca)",
      note: "Najbolje: travanj–lipanj i rujan–listopad. Ljeto vruće.",
      months: [
        { month: "jan", tempC: 8, rainMm: 70 },
        { month: "feb", tempC: 10, rainMm: 65 },
        { month: "mar", tempC: 13, rainMm: 60 },
        { month: "apr", tempC: 16, rainMm: 70 },
        { month: "may", tempC: 21, rainMm: 60 },
        { month: "jun", tempC: 25, rainMm: 40 },
        { month: "jul", tempC: 28, rainMm: 20 },
        { month: "aug", tempC: 28, rainMm: 30 },
        { month: "sep", tempC: 24, rainMm: 65 },
        { month: "oct", tempC: 19, rainMm: 85 },
        { month: "nov", tempC: 14, rainMm: 95 },
        { month: "dec", tempC: 10, rainMm: 85 },
      ],
    },
  ],
},
{
  slug: "mađarska",
  title: "Najbolje vrijeme za posjet Mađarskoj",
  subtitle: "Najugodnije u proljeće i ranu jesen; ljeto može biti vrlo toplo.",
  regions: [
    {
      id: "budimpesta",
      label: "Budimpešta i nizine",
      note: "Najbolje: travanj–lipanj i rujan–listopad. Zimi hladno i maglovito.",
      months: [
        { month: "jan", tempC: 2, rainMm: 35 },
        { month: "feb", tempC: 4, rainMm: 30 },
        { month: "mar", tempC: 9, rainMm: 35 },
        { month: "apr", tempC: 15, rainMm: 45 },
        { month: "may", tempC: 20, rainMm: 60 },
        { month: "jun", tempC: 24, rainMm: 70 },
        { month: "jul", tempC: 27, rainMm: 55 },
        { month: "aug", tempC: 27, rainMm: 55 },
        { month: "sep", tempC: 21, rainMm: 45 },
        { month: "oct", tempC: 15, rainMm: 40 },
        { month: "nov", tempC: 8, rainMm: 45 },
        { month: "dec", tempC: 3, rainMm: 40 },
      ],
    },
  ],
},

{
  slug: "malta",
  title: "Najbolje vrijeme za posjet Malti",
  subtitle: "Proljeće i jesen su idealni; ljeto je vruće i vrlo suho.",
  regions: [
    {
      id: "malta",
      label: "Malta (cijeli otok)",
      note: "Najbolje: travanj–lipanj i rujan–listopad. Zimi blaže, ali vjetrovito i kišovitije.",
      months: [
        { month: "jan", tempC: 15, rainMm: 90 },
        { month: "feb", tempC: 15, rainMm: 65 },
        { month: "mar", tempC: 16, rainMm: 40 },
        { month: "apr", tempC: 18, rainMm: 20 },
        { month: "may", tempC: 22, rainMm: 10 },
        { month: "jun", tempC: 26, rainMm: 5 },
        { month: "jul", tempC: 29, rainMm: 1 },
        { month: "aug", tempC: 30, rainMm: 5 },
        { month: "sep", tempC: 27, rainMm: 35 },
        { month: "oct", tempC: 24, rainMm: 70 },
        { month: "nov", tempC: 20, rainMm: 85 },
        { month: "dec", tempC: 16, rainMm: 95 },
      ],
    },
  ],
},

{
  slug: "nizozemska",
  title: "Najbolje vrijeme za posjet Nizozemskoj",
  subtitle: "Proljeće i ljeto su najugodniji; vrijeme je često promjenjivo.",
  regions: [
    {
      id: "randstad",
      label: "Randstad (Amsterdam, Rotterdam, Haag)",
      note: "Najbolje: travanj–rujan. Uvijek računaj na kišu i vjetar.",
      months: [
        { month: "jan", tempC: 5, rainMm: 70 },
        { month: "feb", tempC: 6, rainMm: 55 },
        { month: "mar", tempC: 9, rainMm: 60 },
        { month: "apr", tempC: 12, rainMm: 45 },
        { month: "may", tempC: 16, rainMm: 55 },
        { month: "jun", tempC: 19, rainMm: 65 },
        { month: "jul", tempC: 21, rainMm: 75 },
        { month: "aug", tempC: 21, rainMm: 80 },
        { month: "sep", tempC: 18, rainMm: 75 },
        { month: "oct", tempC: 14, rainMm: 80 },
        { month: "nov", tempC: 9, rainMm: 85 },
        { month: "dec", tempC: 6, rainMm: 80 },
      ],
    },
  ],
},

{
  slug: "njemačka",
  title: "Najbolje vrijeme za posjet Njemačkoj",
  subtitle: "Najugodnije u kasno proljeće i ranu jesen; sjever je svježiji i vjetrovitiji.",
  regions: [
    {
      id: "juzna",
      label: "Južna Njemačka (München i Bavarska)",
      note: "Najbolje: svibanj–lipanj i rujan. Zimi hladno, u Alpama snijeg.",
      months: [
        { month: "jan", tempC: 1, rainMm: 50 },
        { month: "feb", tempC: 3, rainMm: 45 },
        { month: "mar", tempC: 8, rainMm: 55 },
        { month: "apr", tempC: 12, rainMm: 60 },
        { month: "may", tempC: 17, rainMm: 95 },
        { month: "jun", tempC: 20, rainMm: 110 },
        { month: "jul", tempC: 22, rainMm: 115 },
        { month: "aug", tempC: 22, rainMm: 105 },
        { month: "sep", tempC: 18, rainMm: 80 },
        { month: "oct", tempC: 12, rainMm: 65 },
        { month: "nov", tempC: 6, rainMm: 60 },
        { month: "dec", tempC: 2, rainMm: 55 },
      ],
    },
    {
      id: "sjever",
      label: "Sjever (Hamburg i obala)",
      note: "Najugodnije: svibanj–rujan. Često vjetar i kiša kroz godinu.",
      months: [
        { month: "jan", tempC: 4, rainMm: 70 },
        { month: "feb", tempC: 5, rainMm: 55 },
        { month: "mar", tempC: 8, rainMm: 60 },
        { month: "apr", tempC: 12, rainMm: 45 },
        { month: "may", tempC: 16, rainMm: 55 },
        { month: "jun", tempC: 19, rainMm: 70 },
        { month: "jul", tempC: 21, rainMm: 80 },
        { month: "aug", tempC: 21, rainMm: 85 },
        { month: "sep", tempC: 17, rainMm: 75 },
        { month: "oct", tempC: 12, rainMm: 80 },
        { month: "nov", tempC: 8, rainMm: 80 },
        { month: "dec", tempC: 5, rainMm: 75 },
      ],
    },
  ],
},

{
  slug: "rumunjska",
  title: "Najbolje vrijeme za posjet Rumunjskoj",
  subtitle: "Najugodnije u proljeće i ranu jesen; ljeto u nizini može biti vrlo toplo.",
  regions: [
    {
      id: "bukurest",
      label: "Bukurešt i nizine",
      note: "Najbolje: travanj–lipanj i rujan. Zimi hladno, ljeti vruće.",
      months: [
        { month: "jan", tempC: 1, rainMm: 35 },
        { month: "feb", tempC: 3, rainMm: 30 },
        { month: "mar", tempC: 9, rainMm: 35 },
        { month: "apr", tempC: 15, rainMm: 45 },
        { month: "may", tempC: 20, rainMm: 60 },
        { month: "jun", tempC: 24, rainMm: 70 },
        { month: "jul", tempC: 27, rainMm: 60 },
        { month: "aug", tempC: 27, rainMm: 45 },
        { month: "sep", tempC: 22, rainMm: 45 },
        { month: "oct", tempC: 16, rainMm: 40 },
        { month: "nov", tempC: 9, rainMm: 45 },
        { month: "dec", tempC: 3, rainMm: 40 },
      ],
    },
    {
      id: "transilvanija",
      label: "Transilvanija (Brașov i područje)",
      note: "Najugodnije: svibanj–rujan. Zimi čest snijeg.",
      months: [
        { month: "jan", tempC: -2, rainMm: 40 },
        { month: "feb", tempC: 0, rainMm: 35 },
        { month: "mar", tempC: 5, rainMm: 40 },
        { month: "apr", tempC: 10, rainMm: 55 },
        { month: "may", tempC: 15, rainMm: 80 },
        { month: "jun", tempC: 18, rainMm: 95 },
        { month: "jul", tempC: 20, rainMm: 85 },
        { month: "aug", tempC: 20, rainMm: 70 },
        { month: "sep", tempC: 16, rainMm: 55 },
        { month: "oct", tempC: 10, rainMm: 45 },
        { month: "nov", tempC: 4, rainMm: 45 },
        { month: "dec", tempC: -1, rainMm: 45 },
      ],
    },
  ],
},

{
  slug: "slovačka",
  title: "Najbolje vrijeme za posjet Slovačkoj",
  subtitle: "Planine su hladnije; gradovi su najbolji u proljeće i jesen.",
  regions: [
    {
      id: "bratislava",
      label: "Bratislava i nizine",
      note: "Najugodnije: travanj–lipanj i rujan. Zimi hladno.",
      months: [
        { month: "jan", tempC: 1, rainMm: 35 },
        { month: "feb", tempC: 3, rainMm: 30 },
        { month: "mar", tempC: 8, rainMm: 35 },
        { month: "apr", tempC: 14, rainMm: 40 },
        { month: "may", tempC: 19, rainMm: 60 },
        { month: "jun", tempC: 23, rainMm: 70 },
        { month: "jul", tempC: 25, rainMm: 65 },
        { month: "aug", tempC: 25, rainMm: 70 },
        { month: "sep", tempC: 20, rainMm: 45 },
        { month: "oct", tempC: 14, rainMm: 40 },
        { month: "nov", tempC: 7, rainMm: 45 },
        { month: "dec", tempC: 2, rainMm: 40 },
      ],
    },
    {
      id: "tatry",
      label: "Visoke Tatre",
      note: "Najbolje: lipanj–rujan za planinarenje. Zimi snijeg i skijanje.",
      months: [
        { month: "jan", tempC: -6, rainMm: 55 },
        { month: "feb", tempC: -5, rainMm: 50 },
        { month: "mar", tempC: -1, rainMm: 55 },
        { month: "apr", tempC: 4, rainMm: 70 },
        { month: "may", tempC: 9, rainMm: 110 },
        { month: "jun", tempC: 13, rainMm: 135 },
        { month: "jul", tempC: 15, rainMm: 150 },
        { month: "aug", tempC: 15, rainMm: 140 },
        { month: "sep", tempC: 11, rainMm: 105 },
        { month: "oct", tempC: 6, rainMm: 85 },
        { month: "nov", tempC: 0, rainMm: 70 },
        { month: "dec", tempC: -4, rainMm: 60 },
      ],
    },
  ],
},

{
  slug: "slovenija",
  title: "Najbolje vrijeme za posjet Sloveniji",
  subtitle: "Obala je blaža, Ljubljana i unutrašnjost su svježiji; planine imaju snijeg zimi.",
  regions: [
    {
      id: "ljubljana",
      label: "Ljubljana i unutrašnjost",
      note: "Najugodnije: svibanj–lipanj i rujan. Zimi zna biti hladno i maglovito.",
      months: [
        { month: "jan", tempC: 2, rainMm: 70 },
        { month: "feb", tempC: 4, rainMm: 65 },
        { month: "mar", tempC: 9, rainMm: 80 },
        { month: "apr", tempC: 13, rainMm: 95 },
        { month: "may", tempC: 18, rainMm: 120 },
        { month: "jun", tempC: 22, rainMm: 140 },
        { month: "jul", tempC: 24, rainMm: 120 },
        { month: "aug", tempC: 24, rainMm: 130 },
        { month: "sep", tempC: 19, rainMm: 140 },
        { month: "oct", tempC: 13, rainMm: 120 },
        { month: "nov", tempC: 7, rainMm: 110 },
        { month: "dec", tempC: 3, rainMm: 90 },
      ],
    },
    {
      id: "obala",
      label: "Obala (Piran/Koper)",
      note: "Najugodnije: travanj–lipanj i rujan. Zime blaže, ali kišovite.",
      months: [
        { month: "jan", tempC: 7, rainMm: 90 },
        { month: "feb", tempC: 8, rainMm: 80 },
        { month: "mar", tempC: 11, rainMm: 80 },
        { month: "apr", tempC: 15, rainMm: 95 },
        { month: "may", tempC: 20, rainMm: 90 },
        { month: "jun", tempC: 24, rainMm: 80 },
        { month: "jul", tempC: 27, rainMm: 55 },
        { month: "aug", tempC: 27, rainMm: 85 },
        { month: "sep", tempC: 23, rainMm: 140 },
        { month: "oct", tempC: 17, rainMm: 150 },
        { month: "nov", tempC: 12, rainMm: 150 },
        { month: "dec", tempC: 8, rainMm: 115 },
      ],
    },
  ],
},

{
  slug: "španjolska",
  title: "Najbolje vrijeme za posjet Španjolskoj",
  subtitle: "Kontinent i Kanarski otoci imaju potpuno različite sezone.",
  regions: [
    {
      id: "kontinentalna",
      label: "Kontinentalna Španjolska",
      note: "Najbolje: ožujak–lipanj i rujan–listopad. Srpanj/kolovoz su vrlo vrući u unutrašnjosti.",
      months: [
        { month: "jan", tempC: 10, rainMm: 50 },
        { month: "feb", tempC: 11, rainMm: 45 },
        { month: "mar", tempC: 14, rainMm: 40 },
        { month: "apr", tempC: 16, rainMm: 45 },
        { month: "may", tempC: 20, rainMm: 45 },
        { month: "jun", tempC: 25, rainMm: 25 },
        { month: "jul", tempC: 29, rainMm: 10 },
        { month: "aug", tempC: 29, rainMm: 10 },
        { month: "sep", tempC: 25, rainMm: 30 },
        { month: "oct", tempC: 19, rainMm: 55 },
        { month: "nov", tempC: 14, rainMm: 60 },
        { month: "dec", tempC: 11, rainMm: 55 },
      ],
    },
    {
      id: "kanari",
      label: "Kanarski otoci",
      note: "Odlično gotovo cijele godine. Zimi ugodno, ljeti toplo ali ne ekstremno.",
      months: [
        { month: "jan", tempC: 20, rainMm: 25 },
        { month: "feb", tempC: 20, rainMm: 20 },
        { month: "mar", tempC: 21, rainMm: 15 },
        { month: "apr", tempC: 22, rainMm: 10 },
        { month: "may", tempC: 23, rainMm: 5 },
        { month: "jun", tempC: 25, rainMm: 2 },
        { month: "jul", tempC: 27, rainMm: 1 },
        { month: "aug", tempC: 28, rainMm: 2 },
        { month: "sep", tempC: 27, rainMm: 5 },
        { month: "oct", tempC: 25, rainMm: 15 },
        { month: "nov", tempC: 23, rainMm: 20 },
        { month: "dec", tempC: 21, rainMm: 25 },
      ],
    },
  ],
},
{
  slug: "srbija",
  title: "Najbolje vrijeme za posjet Srbiji",
  subtitle: "Najugodnije u proljeće i ranu jesen; ljeto u nizini zna biti vrlo toplo.",
  regions: [
    {
      id: "beograd",
      label: "Beograd i sjever (Vojvodina)",
      note: "Najbolje: travanj–lipanj i rujan–listopad. Zimi hladno, ljeti sparno.",
      months: [
        { month: "jan", tempC: 3, rainMm: 45 },
        { month: "feb", tempC: 5, rainMm: 40 },
        { month: "mar", tempC: 10, rainMm: 45 },
        { month: "apr", tempC: 15, rainMm: 55 },
        { month: "may", tempC: 20, rainMm: 70 },
        { month: "jun", tempC: 24, rainMm: 85 },
        { month: "jul", tempC: 27, rainMm: 65 },
        { month: "aug", tempC: 27, rainMm: 55 },
        { month: "sep", tempC: 22, rainMm: 55 },
        { month: "oct", tempC: 16, rainMm: 55 },
        { month: "nov", tempC: 10, rainMm: 60 },
        { month: "dec", tempC: 5, rainMm: 55 },
      ],
    },
    {
      id: "jug",
      label: "Jug Srbije (Niš i brdska područja)",
      note: "Svježije od sjevera; ugodno u proljeće i ranu jesen.",
      months: [
        { month: "jan", tempC: 2, rainMm: 45 },
        { month: "feb", tempC: 4, rainMm: 40 },
        { month: "mar", tempC: 9, rainMm: 45 },
        { month: "apr", tempC: 14, rainMm: 55 },
        { month: "may", tempC: 19, rainMm: 70 },
        { month: "jun", tempC: 23, rainMm: 75 },
        { month: "jul", tempC: 26, rainMm: 55 },
        { month: "aug", tempC: 26, rainMm: 45 },
        { month: "sep", tempC: 20, rainMm: 45 },
        { month: "oct", tempC: 14, rainMm: 55 },
        { month: "nov", tempC: 8, rainMm: 60 },
        { month: "dec", tempC: 4, rainMm: 55 },
      ],
    },
  ],
},

{
  slug: "ujedinjeno kraljevstvo",
  title: "Najbolje vrijeme za posjet Ujedinjenom Kraljevstvu",
  subtitle: "Najbolje u kasno proljeće i ljeto, ali vrijeme je promjenjivo kroz cijelu godinu.",
  regions: [
    {
      id: "london",
      label: "Engleska (London i jug)",
      note: "Najugodnije: svibanj–rujan. Računaj na povremenu kišu i vjetar.",
      months: [
        { month: "jan", tempC: 6, rainMm: 55 },
        { month: "feb", tempC: 7, rainMm: 40 },
        { month: "mar", tempC: 9, rainMm: 40 },
        { month: "apr", tempC: 12, rainMm: 45 },
        { month: "may", tempC: 16, rainMm: 50 },
        { month: "jun", tempC: 19, rainMm: 45 },
        { month: "jul", tempC: 22, rainMm: 45 },
        { month: "aug", tempC: 22, rainMm: 50 },
        { month: "sep", tempC: 19, rainMm: 50 },
        { month: "oct", tempC: 15, rainMm: 65 },
        { month: "nov", tempC: 10, rainMm: 60 },
        { month: "dec", tempC: 7, rainMm: 60 },
      ],
    },
    {
      id: "skotska",
      label: "Škotska (Edinburgh/Highlands)",
      note: "Svježije i kišovitije; najbolje: lipanj–kolovoz.",
      months: [
        { month: "jan", tempC: 4, rainMm: 70 },
        { month: "feb", tempC: 5, rainMm: 55 },
        { month: "mar", tempC: 7, rainMm: 60 },
        { month: "apr", tempC: 10, rainMm: 50 },
        { month: "may", tempC: 13, rainMm: 55 },
        { month: "jun", tempC: 16, rainMm: 65 },
        { month: "jul", tempC: 18, rainMm: 80 },
        { month: "aug", tempC: 18, rainMm: 85 },
        { month: "sep", tempC: 15, rainMm: 80 },
        { month: "oct", tempC: 11, rainMm: 90 },
        { month: "nov", tempC: 7, rainMm: 85 },
        { month: "dec", tempC: 5, rainMm: 80 },
      ],
    },
  ],
},

{
  slug: "vatikan",
  title: "Najbolje vrijeme za posjet Vatikanu",
  subtitle: "U praksi vrijedi isto kao i za Rim: proljeće i jesen su najugodniji.",
  regions: [
    {
      id: "vatikan",
      label: "Vatikan (Rim)",
      note: "Najbolje: ožujak–lipanj i rujan–listopad. Ljeti vruće, u zimskim mjesecima više kiše.",
      months: [
        { month: "jan", tempC: 9, rainMm: 75 },
        { month: "feb", tempC: 10, rainMm: 70 },
        { month: "mar", tempC: 13, rainMm: 60 },
        { month: "apr", tempC: 16, rainMm: 55 },
        { month: "may", tempC: 20, rainMm: 45 },
        { month: "jun", tempC: 25, rainMm: 30 },
        { month: "jul", tempC: 28, rainMm: 15 },
        { month: "aug", tempC: 28, rainMm: 20 },
        { month: "sep", tempC: 24, rainMm: 55 },
        { month: "oct", tempC: 19, rainMm: 85 },
        { month: "nov", tempC: 14, rainMm: 95 },
        { month: "dec", tempC: 10, rainMm: 85 },
      ],
    },
  ],
},

{
  slug: "turska",
  title: "Najbolje vrijeme za posjet Turskoj",
  subtitle: "Obala je mediteranska, unutrašnjost ima kontinentalne zime i vruća ljeta.",
  regions: [
    {
      id: "istanbul",
      label: "Istanbul",
      note: "Najugodnije: travanj–lipanj i rujan–listopad. Zimi više kiše i vjetra.",
      months: [
        { month: "jan", tempC: 8, rainMm: 100 },
        { month: "feb", tempC: 8, rainMm: 75 },
        { month: "mar", tempC: 10, rainMm: 70 },
        { month: "apr", tempC: 14, rainMm: 50 },
        { month: "may", tempC: 18, rainMm: 35 },
        { month: "jun", tempC: 23, rainMm: 35 },
        { month: "jul", tempC: 25, rainMm: 25 },
        { month: "aug", tempC: 25, rainMm: 30 },
        { month: "sep", tempC: 22, rainMm: 55 },
        { month: "oct", tempC: 17, rainMm: 80 },
        { month: "nov", tempC: 13, rainMm: 85 },
        { month: "dec", tempC: 10, rainMm: 120 },
      ],
    },
    {
      id: "antalya",
      label: "Mediteranska obala (Antalya)",
      note: "Najbolje: travanj–lipanj i rujan–listopad. Ljeti vrlo vruće i suho, zimi kišovitije.",
      months: [
        { month: "jan", tempC: 11, rainMm: 180 },
        { month: "feb", tempC: 12, rainMm: 120 },
        { month: "mar", tempC: 14, rainMm: 85 },
        { month: "apr", tempC: 18, rainMm: 45 },
        { month: "may", tempC: 22, rainMm: 25 },
        { month: "jun", tempC: 27, rainMm: 10 },
        { month: "jul", tempC: 30, rainMm: 2 },
        { month: "aug", tempC: 30, rainMm: 3 },
        { month: "sep", tempC: 27, rainMm: 15 },
        { month: "oct", tempC: 22, rainMm: 70 },
        { month: "nov", tempC: 17, rainMm: 140 },
        { month: "dec", tempC: 13, rainMm: 200 },
      ],
    },
    {
      id: "kapadokija",
      label: "Kapadokija (unutrašnjost)",
      note: "Najbolje: travanj–lipanj i rujan. Zime hladne, ljeta suha i vruća.",
      months: [
        { month: "jan", tempC: 0, rainMm: 40 },
        { month: "feb", tempC: 2, rainMm: 35 },
        { month: "mar", tempC: 7, rainMm: 35 },
        { month: "apr", tempC: 12, rainMm: 45 },
        { month: "may", tempC: 17, rainMm: 55 },
        { month: "jun", tempC: 21, rainMm: 35 },
        { month: "jul", tempC: 25, rainMm: 10 },
        { month: "aug", tempC: 25, rainMm: 8 },
        { month: "sep", tempC: 20, rainMm: 15 },
        { month: "oct", tempC: 14, rainMm: 35 },
        { month: "nov", tempC: 7, rainMm: 35 },
        { month: "dec", tempC: 2, rainMm: 45 },
      ],
    },
  ],
},

{
  slug: "sad",
  title: "Najbolje vrijeme za posjet SAD-u",
  subtitle: "Odaberi grad/regiju jer su razlike velike po klimama.",
  regions: [
    {
      id: "san-francisco",
      label: "San Francisco",
      note: "Ugodno cijele godine; ljeto je često svježije i maglovito. Zima je kišnija.",
      months: [
        { month: "jan", tempC: 12, rainMm: 110 },
        { month: "feb", tempC: 13, rainMm: 95 },
        { month: "mar", tempC: 14, rainMm: 80 },
        { month: "apr", tempC: 15, rainMm: 35 },
        { month: "may", tempC: 16, rainMm: 20 },
        { month: "jun", tempC: 18, rainMm: 5 },
        { month: "jul", tempC: 18, rainMm: 0 },
        { month: "aug", tempC: 19, rainMm: 2 },
        { month: "sep", tempC: 20, rainMm: 5 },
        { month: "oct", tempC: 18, rainMm: 25 },
        { month: "nov", tempC: 15, rainMm: 65 },
        { month: "dec", tempC: 13, rainMm: 105 },
      ],
    },
    {
      id: "los-angeles",
      label: "Los Angeles",
      note: "Najbolje: ožujak–lipanj i rujan–listopad. Ljeto je suho i toplo, zima blaža ali kišnija.",
      months: [
        { month: "jan", tempC: 14, rainMm: 80 },
        { month: "feb", tempC: 15, rainMm: 65 },
        { month: "mar", tempC: 16, rainMm: 55 },
        { month: "apr", tempC: 18, rainMm: 20 },
        { month: "may", tempC: 20, rainMm: 8 },
        { month: "jun", tempC: 23, rainMm: 2 },
        { month: "jul", tempC: 26, rainMm: 1 },
        { month: "aug", tempC: 27, rainMm: 2 },
        { month: "sep", tempC: 26, rainMm: 5 },
        { month: "oct", tempC: 22, rainMm: 15 },
        { month: "nov", tempC: 18, rainMm: 25 },
        { month: "dec", tempC: 15, rainMm: 65 },
      ],
    },
    {
      id: "las-vegas",
      label: "Las Vegas",
      note: "Najbolje: ožujak–svibanj i rujan–listopad. Ljeti ekstremno vruće.",
      months: [
        { month: "jan", tempC: 9, rainMm: 15 },
        { month: "feb", tempC: 12, rainMm: 15 },
        { month: "mar", tempC: 16, rainMm: 10 },
        { month: "apr", tempC: 21, rainMm: 5 },
        { month: "may", tempC: 27, rainMm: 5 },
        { month: "jun", tempC: 33, rainMm: 2 },
        { month: "jul", tempC: 37, rainMm: 10 },
        { month: "aug", tempC: 36, rainMm: 10 },
        { month: "sep", tempC: 31, rainMm: 7 },
        { month: "oct", tempC: 24, rainMm: 5 },
        { month: "nov", tempC: 16, rainMm: 5 },
        { month: "dec", tempC: 10, rainMm: 10 },
      ],
    },
    {
      id: "new-york",
      label: "New York",
      note: "Najbolje: svibanj–lipanj i rujan–listopad. Zime hladne, ljeta vruća i sparna.",
      months: [
        { month: "jan", tempC: 1, rainMm: 85 },
        { month: "feb", tempC: 3, rainMm: 75 },
        { month: "mar", tempC: 7, rainMm: 95 },
        { month: "apr", tempC: 13, rainMm: 100 },
        { month: "may", tempC: 19, rainMm: 100 },
        { month: "jun", tempC: 24, rainMm: 95 },
        { month: "jul", tempC: 27, rainMm: 115 },
        { month: "aug", tempC: 26, rainMm: 110 },
        { month: "sep", tempC: 22, rainMm: 90 },
        { month: "oct", tempC: 16, rainMm: 90 },
        { month: "nov", tempC: 10, rainMm: 90 },
        { month: "dec", tempC: 4, rainMm: 95 },
      ],
    },
  ],
},

{
  slug: "južnoafrička republika",
  title: "Najbolje vrijeme za posjet Južnoafričkoj Republici",
  subtitle: "Cape Town ima mediteransku klimu, a Kruger je najbolji u sušnoj sezoni.",
  regions: [
    {
      id: "cape-town",
      label: "Cape Town",
      note: "Najbolje: studeni–ožujak (toplo i suho). Zimi (lipanj–kolovoz) više kiše.",
      months: [
        { month: "jan", tempC: 22, rainMm: 15 },
        { month: "feb", tempC: 22, rainMm: 15 },
        { month: "mar", tempC: 21, rainMm: 20 },
        { month: "apr", tempC: 18, rainMm: 40 },
        { month: "may", tempC: 16, rainMm: 70 },
        { month: "jun", tempC: 14, rainMm: 90 },
        { month: "jul", tempC: 13, rainMm: 95 },
        { month: "aug", tempC: 13, rainMm: 80 },
        { month: "sep", tempC: 14, rainMm: 45 },
        { month: "oct", tempC: 16, rainMm: 30 },
        { month: "nov", tempC: 18, rainMm: 20 },
        { month: "dec", tempC: 20, rainMm: 15 },
      ],
    },
    {
      id: "kruger",
      label: "Nacionalni park Kruger",
      note: "Najbolje za safari: svibanj–rujan (sušna sezona, lakše vidjeti životinje). Ljeto je vruće i kišovito.",
      months: [
        { month: "jan", tempC: 27, rainMm: 120 },
        { month: "feb", tempC: 27, rainMm: 95 },
        { month: "mar", tempC: 26, rainMm: 70 },
        { month: "apr", tempC: 24, rainMm: 40 },
        { month: "may", tempC: 22, rainMm: 15 },
        { month: "jun", tempC: 20, rainMm: 5 },
        { month: "jul", tempC: 20, rainMm: 2 },
        { month: "aug", tempC: 22, rainMm: 3 },
        { month: "sep", tempC: 24, rainMm: 10 },
        { month: "oct", tempC: 26, rainMm: 35 },
        { month: "nov", tempC: 27, rainMm: 70 },
        { month: "dec", tempC: 27, rainMm: 110 },
      ],
    },
  ],
},
];
