// utils/countryGrammar.ts

export type CountryGrammar = {
  nominative: string;
  accusative: string;
  genitive: string;
};

const makeForms = (
  nominative: string,
  accusative: string,
  genitive: string
): CountryGrammar => ({
  nominative,
  accusative,
  genitive,
});

export const countryGrammarMap: Record<string, CountryGrammar> = {
  // EUROPA
  Albanija: makeForms("Albanija", "Albaniju", "Albanije"),
  Andora: makeForms("Andora", "Andoru", "Andore"),
  Armenija: makeForms("Armenija", "Armeniju", "Armenije"),
  Austrija: makeForms("Austrija", "Austriju", "Austrije"),
  Azerbajdžan: makeForms("Azerbajdžan", "Azerbajdžan", "Azerbajdžana"),
  Belgija: makeForms("Belgija", "Belgiju", "Belgije"),
  Bjelorusija: makeForms("Bjelorusija", "Bjelorusiju", "Bjelorusije"),
  "Bosna i Hercegovina": makeForms(
    "Bosna i Hercegovina",
    "Bosnu i Hercegovinu",
    "Bosne i Hercegovine"
  ),
  Bugarska: makeForms("Bugarska", "Bugarsku", "Bugarske"),
  Cipar: makeForms("Cipar", "Cipar", "Cipra"),
  "Crna Gora": makeForms("Crna Gora", "Crnu Goru", "Crne Gore"),
  Češka: makeForms("Češka", "Češku", "Češke"),
  Danska: makeForms("Danska", "Dansku", "Danske"),
  Estonija: makeForms("Estonija", "Estoniju", "Estonije"),
  Finska: makeForms("Finska", "Finsku", "Finske"),
  Francuska: makeForms("Francuska", "Francusku", "Francuske"),
  Gruzija: makeForms("Gruzija", "Gruziju", "Gruzije"),
  Grčka: makeForms("Grčka", "Grčku", "Grčke"),
  Hrvatska: makeForms("Hrvatska", "Hrvatsku", "Hrvatske"),
  Irska: makeForms("Irska", "Irsku", "Irske"),
  Island: makeForms("Island", "Island", "Islanda"),
  Italija: makeForms("Italija", "Italiju", "Italije"),
  Kazahstan: makeForms("Kazahstan", "Kazahstan", "Kazahstana"),
  Kosovo: makeForms("Kosovo", "Kosovo", "Kosova"),
  Latvija: makeForms("Latvija", "Latviju", "Latvije"),
  Lihtenštajn: makeForms("Lihtenštajn", "Lihtenštajn", "Lihtenštajna"),
  Litva: makeForms("Litva", "Litvu", "Litve"),
  Luksemburg: makeForms("Luksemburg", "Luksemburg", "Luksemburga"),
  Mađarska: makeForms("Mađarska", "Mađarsku", "Mađarske"),
  Malta: makeForms("Malta", "Maltu", "Malte"),
  Moldavija: makeForms("Moldavija", "Moldaviju", "Moldavije"),
  Monako: makeForms("Monako", "Monako", "Monaka"),
  Nizozemska: makeForms("Nizozemska", "Nizozemsku", "Nizozemske"),
  Njemačka: makeForms("Njemačka", "Njemačku", "Njemačke"),
  Norveška: makeForms("Norveška", "Norvešku", "Norveške"),
  Poljska: makeForms("Poljska", "Poljsku", "Poljske"),
  Portugal: makeForms("Portugal", "Portugal", "Portugala"),
  Rumunjska: makeForms("Rumunjska", "Rumunjsku", "Rumunjske"),
  Rusija: makeForms("Rusija", "Rusiju", "Rusije"),
  "San Marino": makeForms("San Marino", "San Marino", "San Marina"),
  Slovačka: makeForms("Slovačka", "Slovačku", "Slovačke"),
  Slovenija: makeForms("Slovenija", "Sloveniju", "Slovenije"),
  Srbija: makeForms("Srbija", "Srbiju", "Srbije"),
  "Sjeverna Makedonija": makeForms(
    "Sjeverna Makedonija",
    "Sjevernu Makedoniju",
    "Sjeverne Makedonije"
  ),
  Španjolska: makeForms("Španjolska", "Španjolsku", "Španjolske"),
  Švedska: makeForms("Švedska", "Švedsku", "Švedske"),
  Švicarska: makeForms("Švicarska", "Švicarsku", "Švicarske"),
  Turska: makeForms("Turska", "Tursku", "Turske"),
  Ukrajina: makeForms("Ukrajina", "Ukrajinu", "Ukrajine"),
  Vatikan: makeForms("Vatikan", "Vatikan", "Vatikana"),
  "Ujedinjeno Kraljevstvo": makeForms(
    "Ujedinjeno Kraljevstvo",
    "Ujedinjeno Kraljevstvo",
    "Ujedinjenog Kraljevstva"
  ),

  // AZIJA
  Afganistan: makeForms("Afganistan", "Afganistan", "Afganistana"),
  Bahrein: makeForms("Bahrein", "Bahrein", "Bahreina"),
  Bangladeš: makeForms("Bangladeš", "Bangladeš", "Bangladeša"),
  Butan: makeForms("Butan", "Butan", "Butana"),
  Brunej: makeForms("Brunej", "Brunej", "Bruneja"),
  Filipini: makeForms("Filipini", "Filipine", "Filipina"),
  Indija: makeForms("Indija", "Indiju", "Indije"),
  Indonezija: makeForms("Indonezija", "Indoneziju", "Indonezije"),
  Irak: makeForms("Irak", "Irak", "Iraka"),
  Iran: makeForms("Iran", "Iran", "Irana"),
  Izrael: makeForms("Izrael", "Izrael", "Izraela"),
  Japan: makeForms("Japan", "Japan", "Japana"),
  Jemen: makeForms("Jemen", "Jemen", "Jemena"),
  Jordan: makeForms("Jordan", "Jordan", "Jordana"),
  Kambodža: makeForms("Kambodža", "Kambodžu", "Kambodže"),
  Katar: makeForms("Katar", "Katar", "Katara"),
  Kina: makeForms("Kina", "Kinu", "Kine"),
  Kirgistan: makeForms("Kirgistan", "Kirgistan", "Kirgistana"),
  Kuvajt: makeForms("Kuvajt", "Kuvajt", "Kuvajta"),
  Laos: makeForms("Laos", "Laos", "Laosa"),
  Libanon: makeForms("Libanon", "Libanon", "Libanona"),
  Malezija: makeForms("Malezija", "Maleziju", "Malezije"),
  Maldivi: makeForms("Maldivi", "Maldive", "Maldiva"),
  Mongolija: makeForms("Mongolija", "Mongoliju", "Mongolije"),
  Mjanmar: makeForms("Mjanmar", "Mjanmar", "Mjanmara"),
  Nepal: makeForms("Nepal", "Nepal", "Nepala"),
  Oman: makeForms("Oman", "Oman", "Omana"),
  Pakistan: makeForms("Pakistan", "Pakistan", "Pakistana"),
  Palestina: makeForms("Palestina", "Palestinu", "Palestine"),
  "Saudijska Arabija": makeForms(
    "Saudijska Arabija",
    "Saudijsku Arabiju",
    "Saudijske Arabije"
  ),
  Singapur: makeForms("Singapur", "Singapur", "Singapura"),
  Sirija: makeForms("Sirija", "Siriju", "Sirije"),
  "Sjeverna Koreja": makeForms(
    "Sjeverna Koreja",
    "Sjevernu Koreju",
    "Sjeverne Koreje"
  ),
  "Južna Koreja": makeForms(
    "Južna Koreja",
    "Južnu Koreju",
    "Južne Koreje"
  ),
  "Šri Lanka": makeForms("Šri Lanka", "Šri Lanku", "Šri Lanke"),
  Tadžikistan: makeForms("Tadžikistan", "Tadžikistan", "Tadžikistana"),
  Tajland: makeForms("Tajland", "Tajland", "Tajlanda"),
  Tajvan: makeForms("Tajvan", "Tajvan", "Tajvana"),
  Turkmenistan: makeForms("Turkmenistan", "Turkmenistan", "Turkmenistana"),
  "Ujedinjeni Arapski Emirati": makeForms(
    "Ujedinjeni Arapski Emirati",
    "Ujedinjene Arapske Emirate",
    "Ujedinjenih Arapskih Emirata"
  ),
  Uzbekistan: makeForms("Uzbekistan", "Uzbekistan", "Uzbekistana"),
  Vijetnam: makeForms("Vijetnam", "Vijetnam", "Vijetnama"),

  // AFRIKA
  Alžir: makeForms("Alžir", "Alžir", "Alžira"),
  Angola: makeForms("Angola", "Angolu", "Angole"),
  Benin: makeForms("Benin", "Benin", "Benina"),
  Bocvana: makeForms("Bocvana", "Bocvanu", "Bocvane"),
  "Burkina Faso": makeForms(
    "Burkina Faso",
    "Burkina Faso",
    "Burkine Faso"
  ),
  Burundi: makeForms("Burundi", "Burundi", "Burundija"),
  Čad: makeForms("Čad", "Čad", "Čada"),
  Džibuti: makeForms("Džibuti", "Džibuti", "Džibutija"),
  Egipat: makeForms("Egipat", "Egipat", "Egipta"),
  Eritreja: makeForms("Eritreja", "Eritreju", "Eritreje"),
  Esvatini: makeForms("Esvatini", "Esvatini", "Esvatinija"),
  Etiopija: makeForms("Etiopija", "Etiopiju", "Etiopije"),
  Gabon: makeForms("Gabon", "Gabon", "Gabona"),
  Gambija: makeForms("Gambija", "Gambiju", "Gambije"),
  Gana: makeForms("Gana", "Ganu", "Gane"),
  Gvineja: makeForms("Gvineja", "Gvineju", "Gvineje"),
  "Gvineja Bisau": makeForms(
    "Gvineja Bisau",
    "Gvineju Bisau",
    "Gvineje Bisau"
  ),
  Kamerun: makeForms("Kamerun", "Kamerun", "Kameruna"),
  Kenija: makeForms("Kenija", "Keniju", "Kenije"),
  Komori: makeForms("Komori", "Komore", "Komora"),
  Kongo: makeForms("Kongo", "Kongo", "Konga"),
  Lesoto: makeForms("Lesoto", "Lesoto", "Lesota"),
  Liberija: makeForms("Liberija", "Liberiju", "Liberije"),
  Libija: makeForms("Libija", "Libiju", "Libije"),
  Madagaskar: makeForms("Madagaskar", "Madagaskar", "Madagaskara"),
  Malavi: makeForms("Malavi", "Malavi", "Malavija"),
  Mali: makeForms("Mali", "Mali", "Malija"),
  Maroko: makeForms("Maroko", "Maroko", "Maroka"),
  Mauricijus: makeForms("Mauricijus", "Mauricijus", "Mauricijusa"),
  Mauritanija: makeForms("Mauritanija", "Mauritaniju", "Mauritanije"),
  Mozambik: makeForms("Mozambik", "Mozambik", "Mozambika"),
  Namibija: makeForms("Namibija", "Namibiju", "Namibije"),
  Niger: makeForms("Niger", "Niger", "Nigera"),
  Nigerija: makeForms("Nigerija", "Nigeriju", "Nigerije"),
  "Obala Bjelokosti": makeForms(
    "Obala Bjelokosti",
    "Obalu Bjelokosti",
    "Obale Bjelokosti"
  ),
  Ruanda: makeForms("Ruanda", "Ruandu", "Ruande"),
  "Sao Tome i Principe": makeForms(
    "Sao Tome i Principe",
    "Sao Tome i Principe",
    "Sao Tome i Principa"
  ),
  Senegal: makeForms("Senegal", "Senegal", "Senegala"),
  Sejšeli: makeForms("Sejšeli", "Sejšele", "Sejšela"),
  "Sierra Leone": makeForms(
    "Sierra Leone",
    "Sierra Leone",
    "Sierre Leone"
  ),
  Somalija: makeForms("Somalija", "Somaliju", "Somalije"),
  "Srednjoafrička Republika": makeForms(
    "Srednjoafrička Republika",
    "Srednjoafričku Republiku",
    "Srednjoafričke Republike"
  ),
  Sudan: makeForms("Sudan", "Sudan", "Sudana"),
  Tanzanija: makeForms("Tanzanija", "Tanzaniju", "Tanzanije"),
  Togo: makeForms("Togo", "Togo", "Toga"),
  Tunis: makeForms("Tunis", "Tunis", "Tunisa"),
  Uganda: makeForms("Uganda", "Ugandu", "Ugande"),
  Zambija: makeForms("Zambija", "Zambiju", "Zambije"),
  Zimbabve: makeForms("Zimbabve", "Zimbabve", "Zimbabvea"),
  "Južni Sudan": makeForms(
    "Južni Sudan",
    "Južni Sudan",
    "Južnog Sudana"
  ),
  "Južnoafrička Republika": makeForms(
    "Južnoafrička Republika",
    "Južnoafričku Republiku",
    "Južnoafričke Republike"
  ),
  "Demokratska Republika Kongo": makeForms(
    "Demokratska Republika Kongo",
    "Demokratsku Republiku Kongo",
    "Demokratske Republike Kongo"
  ),
  "Ekvatorska Gvineja": makeForms(
    "Ekvatorska Gvineja",
    "Ekvatorsku Gvineju",
    "Ekvatorske Gvineje"
  ),

  // SJEVERNA AMERIKA
  "Antigua i Barbuda": makeForms(
    "Antigua i Barbuda",
    "Antiguu i Barbudu",
    "Antigue i Barbude"
  ),
  Bahami: makeForms("Bahami", "Bahame", "Bahama"),
  Barbados: makeForms("Barbados", "Barbados", "Barbadosa"),
  Belize: makeForms("Belize", "Belize", "Belizea"),
  Kanada: makeForms("Kanada", "Kanadu", "Kanade"),
  Kostarika: makeForms("Kostarika", "Kostariku", "Kostarike"),
  Kuba: makeForms("Kuba", "Kubu", "Kube"),
  Dominika: makeForms("Dominika", "Dominiku", "Dominike"),
  "Dominikanska Republika": makeForms(
    "Dominikanska Republika",
    "Dominikansku Republiku",
    "Dominikanske Republike"
  ),
  Salvador: makeForms("Salvador", "Salvador", "Salvadora"),
  Grenada: makeForms("Grenada", "Grenadu", "Grenade"),
  Gvatemala: makeForms("Gvatemala", "Gvatemalu", "Gvatemale"),
  Haiti: makeForms("Haiti", "Haiti", "Haitija"),
  Honduras: makeForms("Honduras", "Honduras", "Hondurasa"),
  Jamajka: makeForms("Jamajka", "Jamajku", "Jamajke"),
  Meksiko: makeForms("Meksiko", "Meksiko", "Meksika"),
  Nikaragva: makeForms("Nikaragva", "Nikaragvu", "Nikaragve"),
  Panama: makeForms("Panama", "Panamu", "Paname"),
  "SAD": makeForms("SAD", "SAD", "SAD-a"),
  "Sveti Kristofor i Nevis": makeForms(
    "Sveti Kristofor i Nevis",
    "Sveti Kristofor i Nevis",
    "Svetog Kristofora i Nevisa"
  ),
  "Sveta Lucija": makeForms(
    "Sveta Lucija",
    "Svetu Luciju",
    "Svete Lucije"
  ),
  "Sveti Vincent i Grenadini": makeForms(
    "Sveti Vincent i Grenadini",
    "Sveti Vincent i Grenadine",
    "Svetog Vincenta i Grenadina"
  ),
  "Trinidad i Tobago": makeForms(
    "Trinidad i Tobago",
    "Trinidad i Tobago",
    "Trinidada i Tobaga"
  ),

  // JUŽNA AMERIKA
  Argentina: makeForms("Argentina", "Argentinu", "Argentine"),
  Bolivija: makeForms("Bolivija", "Boliviju", "Bolivije"),
  Brazil: makeForms("Brazil", "Brazil", "Brazila"),
  Čile: makeForms("Čile", "Čile", "Čilea"),
  Ekvador: makeForms("Ekvador", "Ekvador", "Ekvadora"),
  Gvajana: makeForms("Gvajana", "Gvajanu", "Gvajane"),
  Kolumbija: makeForms("Kolumbija", "Kolumbiju", "Kolumbije"),
  Paragvaj: makeForms("Paragvaj", "Paragvaj", "Paragvaja"),
  Peru: makeForms("Peru", "Peru", "Perua"),
  Surinam: makeForms("Surinam", "Surinam", "Surinama"),
  Urugvaj: makeForms("Urugvaj", "Urugvaj", "Urugvaja"),
  Venezuela: makeForms("Venezuela", "Venezuelu", "Venezuele"),

  // OCEANIJA
  Australija: makeForms("Australija", "Australiju", "Australije"),
  Fidži: makeForms("Fidži", "Fidži", "Fidžija"),
  Kiribati: makeForms("Kiribati", "Kiribati", "Kiribatija"),
  "Maršalovi Otoci": makeForms(
    "Maršalovi Otoci",
    "Maršalove Otoke",
    "Maršalovih Otoka"
  ),
  Mikronezija: makeForms("Mikronezija", "Mikroneziju", "Mikronezije"),
  Nauru: makeForms("Nauru", "Nauru", "Naurua"),
  "Novi Zeland": makeForms(
    "Novi Zeland",
    "Novi Zeland",
    "Novog Zelanda"
  ),
  Palau: makeForms("Palau", "Palau", "Palaua"),
  "Papua Nova Gvineja": makeForms(
    "Papua Nova Gvineja",
    "Papuu Novu Gvineju",
    "Papue Nove Gvineje"
  ),
  Samoa: makeForms("Samoa", "Samou", "Samoe"),
  "Solomonovi Otoci": makeForms(
    "Solomonovi Otoci",
    "Solomonove Otoke",
    "Solomonovih Otoka"
  ),
  Tonga: makeForms("Tonga", "Tongu", "Tonge"),
  Tuvalu: makeForms("Tuvalu", "Tuvalu", "Tuvalua"),
  Vanuatu: makeForms("Vanuatu", "Vanuatu", "Vanuatua"),
};

const countryAliases: Record<string, string> = {
  // lowercase / slug friendly
  afganistan: "Afganistan",
  albanija: "Albanija",
  alžir: "Alžir",
  alzir: "Alžir",
  andora: "Andora",
  angola: "Angola",
  "antigua i barbuda": "Antigua i Barbuda",
  argentina: "Argentina",
  armenija: "Armenija",
  australija: "Australija",
  austrija: "Austrija",
  azerbajdžan: "Azerbajdžan",
  azerbajdzan: "Azerbajdžan",
  bahami: "Bahami",
  bahrein: "Bahrein",
  bangladeš: "Bangladeš",
  banglades: "Bangladeš",
  barbados: "Barbados",
  belgija: "Belgija",
  belize: "Belize",
  bjelorusija: "Bjelorusija",
  benin: "Benin",
  "bosna i hercegovina": "Bosna i Hercegovina",
  bocvana: "Bocvana",
  bolivija: "Bolivija",
  brazil: "Brazil",
  brunej: "Brunej",
  bugarska: "Bugarska",
  "burkina faso": "Burkina Faso",
  burundi: "Burundi",
  butan: "Butan",
  čad: "Čad",
  cad: "Čad",
  "crna gora": "Crna Gora",
  cipar: "Cipar",
  češka: "Češka",
  ceska: "Češka",
  čile: "Čile",
  cile: "Čile",
  danska: "Danska",
  "demokratska republika kongo": "Demokratska Republika Kongo",
  dominika: "Dominika",
  "dominikanska republika": "Dominikanska Republika",
  džibuti: "Džibuti",
  dzibuti: "Džibuti",
  egipat: "Egipat",
  ekvador: "Ekvador",
  "ekvatorska gvineja": "Ekvatorska Gvineja",
  eritreja: "Eritreja",
  estonija: "Estonija",
  esvatini: "Esvatini",
  etiopija: "Etiopija",
  fidži: "Fidži",
  fidzi: "Fidži",
  filipini: "Filipini",
  finska: "Finska",
  francuska: "Francuska",
  gabon: "Gabon",
  gambija: "Gambija",
  gana: "Gana",
  grčka: "Grčka",
  grcka: "Grčka",
  grenada: "Grenada",
  gruzija: "Gruzija",
  gvajana: "Gvajana",
  gvatemala: "Gvatemala",
  gvineja: "Gvineja",
  "gvineja bisau": "Gvineja Bisau",
  haiti: "Haiti",
  honduras: "Honduras",
  hrvatska: "Hrvatska",
  indija: "Indija",
  indonezija: "Indonezija",
  irak: "Irak",
  iran: "Iran",
  irska: "Irska",
  island: "Island",
  italija: "Italija",
  izrael: "Izrael",
  jamajka: "Jamajka",
  japan: "Japan",
  jemen: "Jemen",
  jordan: "Jordan",
  "južna afrika": "Južnoafrička Republika",
  "juzna afrika": "Južnoafrička Republika",
  "južna koreja": "Južna Koreja",
  "juzna koreja": "Južna Koreja",
  "južni sudan": "Južni Sudan",
  "juzni sudan": "Južni Sudan",
  "južnoafrička republika": "Južnoafrička Republika",
  "juznoafricka republika": "Južnoafrička Republika",
  kambodža: "Kambodža",
  kambodza: "Kambodža",
  kamerun: "Kamerun",
  kanada: "Kanada",
  katar: "Katar",
  kazahstan: "Kazahstan",
  kenija: "Kenija",
  kina: "Kina",
  kirgistan: "Kirgistan",
  kiribati: "Kiribati",
  kolumbija: "Kolumbija",
  komori: "Komori",
  kongo: "Kongo",
  kosovo: "Kosovo",
  kostarika: "Kostarika",
  kuba: "Kuba",
  kuvajt: "Kuvajt",
  laos: "Laos",
  latvija: "Latvija",
  lesoto: "Lesoto",
  libanon: "Libanon",
  liberija: "Liberija",
  libija: "Libija",
  lihtenštajn: "Lihtenštajn",
  lihtenstajn: "Lihtenštajn",
  litva: "Litva",
  luksemburg: "Luksemburg",
  mađarska: "Mađarska",
  madagaskar: "Madagaskar",
  malavi: "Malavi",
  malezija: "Malezija",
  maldivi: "Maldivi",
  mali: "Mali",
  malta: "Malta",
  maroko: "Maroko",
  "maršalovi otoci": "Maršalovi Otoci",
  "marsalovi otoci": "Maršalovi Otoci",
  mauricijus: "Mauricijus",
  mauritanija: "Mauritanija",
  meksiko: "Meksiko",
  mikronezija: "Mikronezija",
  mjanmar: "Mjanmar",
  moldavija: "Moldavija",
  monako: "Monako",
  mongolija: "Mongolija",
  mozambik: "Mozambik",
  namibija: "Namibija",
  nauru: "Nauru",
  nepal: "Nepal",
  niger: "Niger",
  nigerija: "Nigerija",
  nikaragva: "Nikaragva",
  nizozemska: "Nizozemska",
  njemačka: "Njemačka",
  njemacka: "Njemačka",
  norveška: "Norveška",
  norveska: "Norveška",
  "novi zeland": "Novi Zeland",
  "obala bjelokosti": "Obala Bjelokosti",
  oman: "Oman",
  pakistan: "Pakistan",
  palau: "Palau",
  palestina: "Palestina",
  panama: "Panama",
  "papua nova gvineja": "Papua Nova Gvineja",
  paragvaj: "Paragvaj",
  peru: "Peru",
  poljska: "Poljska",
  portugal: "Portugal",
  rumunjska: "Rumunjska",
  ruanda: "Ruanda",
  rusija: "Rusija",
  "san marino": "San Marino",
  "sao tome i principe": "Sao Tome i Principe",
  "saudijska arabija": "Saudijska Arabija",
  "sierra leone": "Sierra Leone",
  singapur: "Singapur",
  sirija: "Sirija",
  slovačka: "Slovačka",
  slovacka: "Slovačka",
  slovenija: "Slovenija",
  "solomonovi otoci": "Solomonovi Otoci",
  somalija: "Somalija",
  srbija: "Srbija",
  "srednjoafrička republika": "Srednjoafrička Republika",
  "srednjoafricka republika": "Srednjoafrička Republika",
  sudan: "Sudan",
  surinam: "Surinam",
  "sveta lucija": "Sveta Lucija",
  "sveti kristofor i nevis": "Sveti Kristofor i Nevis",
  "sveti vincent i grenadini": "Sveti Vincent i Grenadini",
  španjolska: "Španjolska",
  spanjolska: "Španjolska",
  "sjeverna koreja": "Sjeverna Koreja",
  "sjeverna makedonija": "Sjeverna Makedonija",
  "sri lanka": "Šri Lanka",
  "šri lanka": "Šri Lanka",
  švedska: "Švedska",
  svedska: "Švedska",
  švicarska: "Švicarska",
  svicarska: "Švicarska",
  tadžikistan: "Tadžikistan",
  tadzikistan: "Tadžikistan",
  tajland: "Tajland",
  tajvan: "Tajvan",
  tanzanija: "Tanzanija",
  togo: "Togo",
  tonga: "Tonga",
  "trinidad i tobago": "Trinidad i Tobago",
  تونس: "Tunis",
  tunis: "Tunis",
  turska: "Turska",
  turkmenistan: "Turkmenistan",
  tuvalu: "Tuvalu",
  uganda: "Uganda",
  ukrajina: "Ukrajina",
  "ujedinjeni arapski emirati": "Ujedinjeni Arapski Emirati",
  "ujedinjeno kraljevstvo": "Ujedinjeno Kraljevstvo",
  urugvaj: "Urugvaj",
  uzbekistan: "Uzbekistan",
  vanuatu: "Vanuatu",
  vatikan: "Vatikan",
  venezuela: "Venezuela",
  vijetnam: "Vijetnam",
  zambija: "Zambija",
  zimbabve: "Zimbabve",
};

const normalizeCountryName = (countryName: string): string => {
  if (!countryName) return "";

  const trimmed = countryName.trim().replace(/\s+/g, " ");
  return countryAliases[trimmed] || countryAliases[trimmed.toLowerCase()] || trimmed;
};

export const getCountryAccusative = (countryName: string): string => {
  const normalized = normalizeCountryName(countryName);
  return countryGrammarMap[normalized]?.accusative || normalized || countryName;
};

export const getCountryGenitive = (countryName: string): string => {
  const normalized = normalizeCountryName(countryName);
  return countryGrammarMap[normalized]?.genitive || normalized || countryName;
};

export const getCountryGrammar = (
  countryName: string
): CountryGrammar | null => {
  const normalized = normalizeCountryName(countryName);
  return countryGrammarMap[normalized] || null;
};