export const countries = [
  { eng_name: "Albania", cro_name: "Albanija" },
  { eng_name: "Andorra", cro_name: "Andora" },
  { eng_name: "Austria", cro_name: "Austrija" },
  { eng_name: "Australia", cro_name: "Australija" },
  { eng_name: "Belarus", cro_name: "Bjelorusija" },
  { eng_name: "Belgium", cro_name: "Belgija" },
  { eng_name: "Bosnia and Herz.", cro_name: "Bosna i Hercegovina" },
  { eng_name: "Bulgaria", cro_name: "Bugarska" },
  { eng_name: "Croatia", cro_name: "Hrvatska" },
  { eng_name: "Cyprus", cro_name: "Cipar" },
  { eng_name: "Czech Rep.", cro_name: "Češka" },
  { eng_name: "Denmark", cro_name: "Danska" },
  { eng_name: "Estonia", cro_name: "Estonija" },
  { eng_name: "Finland", cro_name: "Finska" },
  { eng_name: "France", cro_name: "Francuska" },
  { eng_name: "Germany", cro_name: "Njemačka" },
  { eng_name: "Greece", cro_name: "Grčka" },
  { eng_name: "Hungary", cro_name: "Mađarska" },
  { eng_name: "Iceland", cro_name: "Island" },
  { eng_name: "Ireland", cro_name: "Irska" },
  { eng_name: "Italy", cro_name: "Italija" },
  { eng_name: "Latvia", cro_name: "Latvija" },
  { eng_name: "Liechtenstein", cro_name: "Lihtenštajn" },
  { eng_name: "Lithuania", cro_name: "Litva" },
  { eng_name: "Luxembourg", cro_name: "Luksemburg" },
  { eng_name: "Malta", cro_name: "Malta" },
  { eng_name: "Moldova", cro_name: "Moldavija" },
  { eng_name: "Monaco", cro_name: "Monako" },
  { eng_name: "Montenegro", cro_name: "Crna Gora" },
  { eng_name: "Netherlands", cro_name: "Nizozemska" },
  { eng_name: "North Macedonia", cro_name: "Sjeverna Makedonija" },
  { eng_name: "Norway", cro_name: "Norveška" },
  { eng_name: "Poland", cro_name: "Poljska" },
  { eng_name: "Portugal", cro_name: "Portugal" },
  { eng_name: "Romania", cro_name: "Rumunjska" },
  { eng_name: "Russia", cro_name: "Rusija" },
  { eng_name: "San Marino", cro_name: "San Marino" },
  { eng_name: "Serbia", cro_name: "Srbija" },
  { eng_name: "Slovakia", cro_name: "Slovačka" },
  { eng_name: "Slovenia", cro_name: "Slovenija" },
  { eng_name: "Spain", cro_name: "Španjolska" },
  { eng_name: "Sweden", cro_name: "Švedska" },
  { eng_name: "Switzerland", cro_name: "Švicarska" },
  { eng_name: "Ukraine", cro_name: "Ukrajina" },
  { eng_name: "United Kingdom", cro_name: "Ujedinjeno Kraljevstvo" },
  { eng_name: "Vatican City", cro_name: "Vatikan" },
  { eng_name: "N. Cyprus", cro_name: "Cipar" },
  { eng_name: "Turkey", cro_name: "Turska" },
  { eng_name: "Kosovo", cro_name: "Kosovo" },
  { eng_name: "Luxembourg", cro_name: "Luksemburg" },
  { eng_name: "Macedonia", cro_name: "Makedonija" },

  //africke zemlje

  { eng_name: "Algeria", cro_name: "Alžir" },
  { eng_name: "Angola", cro_name: "Angola" },
  { eng_name: "Benin", cro_name: "Benin" },
  { eng_name: "Botswana", cro_name: "Bocvana" },
  { eng_name: "Burkina Faso", cro_name: "Burkina Faso" },
  { eng_name: "Burundi", cro_name: "Burundi" },
  { eng_name: "Cabo Verde", cro_name: "Zelenortska Republika" },
  { eng_name: "Cameroon", cro_name: "Kamerun" },
  {
    eng_name: "Central African Republic",
    cro_name: "Srednjoafrička Republika",
  },
  { eng_name: "Chad", cro_name: "Čad" },
  { eng_name: "Comoros", cro_name: "Komori" },
  { eng_name: "Congo", cro_name: "Kongo" },
  { eng_name: "Cote d'Ivoire", cro_name: "Obala Bjelokosti" },
  { eng_name: "Djibouti", cro_name: "Džibuti" },
  { eng_name: "Egypt", cro_name: "Egipat" },
  { eng_name: "Equatorial Guinea", cro_name: "Ekvatorska Gvineja" },
  { eng_name: "Eritrea", cro_name: "Eritreja" },
  { eng_name: "Eswatini", cro_name: "Esvatini" },
  { eng_name: "Ethiopia", cro_name: "Etiopija" },
  { eng_name: "Gabon", cro_name: "Gabon" },
  { eng_name: "Gambia", cro_name: "Gambija" },
  { eng_name: "Ghana", cro_name: "Gana" },
  { eng_name: "Guinea", cro_name: "Gvineja" },
  { eng_name: "Guinea-Bissau", cro_name: "Gvineja Bisau" },
  { eng_name: "Kenya", cro_name: "Kenija" },
  { eng_name: "Lesotho", cro_name: "Lesoto" },
  { eng_name: "Liberia", cro_name: "Liberija" },
  { eng_name: "Libya", cro_name: "Libija" },
  { eng_name: "Madagascar", cro_name: "Madagaskar" },
  { eng_name: "Malawi", cro_name: "Malavi" },
  { eng_name: "Mali", cro_name: "Mali" },
  { eng_name: "Mauritania", cro_name: "Mauritanija" },
  { eng_name: "Mauritius", cro_name: "Mauricijus" },
  { eng_name: "Morocco", cro_name: "Maroko" },
  { eng_name: "Mozambique", cro_name: "Mozambik" },
  { eng_name: "Namibia", cro_name: "Namibija" },
  { eng_name: "Niger", cro_name: "Niger" },
  { eng_name: "Nigeria", cro_name: "Nigerija" },
  { eng_name: "Rwanda", cro_name: "Ruanda" },
  { eng_name: "Sao Tome and Principe", cro_name: "Sveti Toma i Princip" },
  { eng_name: "Senegal", cro_name: "Senegal" },
  { eng_name: "Seychelles", cro_name: "Sejšeli" },
  { eng_name: "Sierra Leone", cro_name: "Sijera Leone" },
  { eng_name: "Somalia", cro_name: "Somalija" },
  { eng_name: "South Africa", cro_name: "Južnoafrička Republika" },
  { eng_name: "South Sudan", cro_name: "Južni Sudan" },
  { eng_name: "Sudan", cro_name: "Sudan" },
  { eng_name: "Tanzania", cro_name: "Tanzanija" },
  { eng_name: "Togo", cro_name: "Togo" },
  { eng_name: "Tunisia", cro_name: "Tunis" },
  { eng_name: "Uganda", cro_name: "Uganda" },
  { eng_name: "Zambia", cro_name: "Zambija" },
  { eng_name: "Zimbabwe", cro_name: "Zimbabve" },

  //azijske zemlje

  { eng_name: "Afghanistan", cro_name: "Afganistan" },
  { eng_name: "Armenia", cro_name: "Armenija" },
  { eng_name: "Azerbaijan", cro_name: "Azerbajdžan" },
  { eng_name: "Bahrain", cro_name: "Bahrein" },
  { eng_name: "Bangladesh", cro_name: "Bangladeš" },
  { eng_name: "Bhutan", cro_name: "Butan" },
  { eng_name: "Brunei", cro_name: "Brunej" },
  { eng_name: "Cambodia", cro_name: "Kambodža" },
  { eng_name: "China", cro_name: "Kina" },
  { eng_name: "Georgia", cro_name: "Gruzija" },
  { eng_name: "India", cro_name: "Indija" },
  { eng_name: "Indonesia", cro_name: "Indonezija" },
  { eng_name: "Iran", cro_name: "Iran" },
  { eng_name: "Iraq", cro_name: "Irak" },
  { eng_name: "Israel", cro_name: "Izrael" },
  { eng_name: "Japan", cro_name: "Japan" },
  { eng_name: "Jordan", cro_name: "Jordan" },
  { eng_name: "Kazakhstan", cro_name: "Kazahstan" },
  { eng_name: "Kuwait", cro_name: "Kuvajt" },
  { eng_name: "Kyrgyzstan", cro_name: "Kirgistan" },
  { eng_name: "Laos", cro_name: "Laos" },
  { eng_name: "Lebanon", cro_name: "Libanon" },
  { eng_name: "Malaysia", cro_name: "Malezija" },
  { eng_name: "Maldives", cro_name: "Maldivi" },
  { eng_name: "Mongolia", cro_name: "Mongolija" },
  { eng_name: "Myanmar", cro_name: "Mjanmar" },
  { eng_name: "Nepal", cro_name: "Nepal" },
  { eng_name: "North Korea", cro_name: "Sjeverna Koreja" },
  { eng_name: "Oman", cro_name: "Oman" },
  { eng_name: "Pakistan", cro_name: "Pakistan" },
  { eng_name: "Palestine", cro_name: "Palestina" },
  { eng_name: "Philippines", cro_name: "Filipini" },
  { eng_name: "Qatar", cro_name: "Katar" },
  { eng_name: "Saudi Arabia", cro_name: "Saudijska Arabija" },
  { eng_name: "Singapore", cro_name: "Singapur" },
  { eng_name: "South Korea", cro_name: "Južna Koreja" },
  { eng_name: "Sri Lanka", cro_name: "Šri Lanka" },
  { eng_name: "Syria", cro_name: "Sirija" },
  { eng_name: "Taiwan", cro_name: "Tajvan" },
  { eng_name: "Tajikistan", cro_name: "Tadžikistan" },
  { eng_name: "Thailand", cro_name: "Tajland" },
  { eng_name: "Timor-Leste", cro_name: "Istočni Timor" },
  { eng_name: "Turkmenistan", cro_name: "Turkmenistan" },
  { eng_name: "United Arab Emirates", cro_name: "Ujedinjeni Arapski Emirati" },
  { eng_name: "Uzbekistan", cro_name: "Uzbekistan" },
  { eng_name: "Vietnam", cro_name: "Vijetnam" },
  { eng_name: "Yemen", cro_name: "Jemen" },

  //juzna amerika

  { eng_name: "Argentina", cro_name: "Argentina" },
  { eng_name: "Bolivia", cro_name: "Bolivija" },
  { eng_name: "Brazil", cro_name: "Brazil" },
  { eng_name: "Chile", cro_name: "Čile" },
  { eng_name: "Colombia", cro_name: "Kolumbija" },
  { eng_name: "Ecuador", cro_name: "Ekvador" },
  { eng_name: "Guyana", cro_name: "Gvajana" },
  { eng_name: "Paraguay", cro_name: "Paragvaj" },
  { eng_name: "Peru", cro_name: "Peru" },
  { eng_name: "Suriname", cro_name: "Surinam" },
  { eng_name: "Uruguay", cro_name: "Urugvaj" },
  { eng_name: "Venezuela", cro_name: "Venezuela" },

  // sjeverna amerika
  { eng_name: "United States", cro_name: "SAD" },
  { eng_name: "Canada", cro_name: "Kanada" },
];
